# -*- coding: utf-8 -*-
"""Animal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1phCJebAjovvBwla97bd0i8vn7hDrukbT
"""

animais = [ ]

animal = input("Digite o nome de seu animal de estamação ou digite 0 se não tiver nenhum:    ")

while animal != "0":
  especie = input("Digite a espécie desse animal:     ")
  animais.append([animal, especie])
  animal = input("Se tiver mais animais, digite o nome dele. Ou digite 0 se não tiver:     ")

if len(animais) == 0:
  print('\n\nVocê não tem animais')
else:
  print("\n\nVocê tem os seguintes animais:        ")
  for animal in animais:
    print("- Nome:", animal[0],  "| Espécie:", animal[1])

