# -*- coding: utf-8 -*-
"""Clima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RPuzOH5KXplZQM7awL89omQvu9hH1v04
"""

horario = 'manhã'
clima = 'chuvoso'
temperatura = 'frio'

if horario == 'manhã' or horario ==   'tarde':
  if clima == 'ensolarado' and temperatura ==  'quente':
    print('uma piscina cairia bem')

  if (clima == 'ensolarado' or clima == 'nublado') and (temperatura == 'amena' or temperatura == 'frio'):
    print('seria legal praticar algum esporte')

  if clima == 'chuvoso':
    print('aproveite para estudar Python')
else:
  if clima == 'chuvoso':
    print('que tal um filme, série ou jogatina?')
  else: 
    print('um jantar fora seria interessante')

