# -*- coding: utf-8 -*-
"""JornadaFaixaPretaAula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VB-yXUaYhdiAdUsZFEIKLJeGxvaK0PRZ
"""



"""# Condicionais

Principal forma de atribuir uma lógica ao seu código.

Basicamente é uma tomada de decisão, caso a condição seja verdadeira.

Ex: 
- Se o dia estiver quente:
  - Vou tomar um sorvete
  - Vou a praia

- Do contrário (se não)
  - comer chocolate
  - maratonar Netflix
"""

temperatura= 'quente'
print(temperatura)

if temperatura == 'quente':
  print('Vou tomar sorvete')
  print('Vou a praia')

else:
  print('Vou comer')
  print('Vou ver TV')

horario= 'noite'
if horario == 'manhã':
  print('O sol está quente')
elif horario == 'tarde':
  print('Chegará o por do sol')
else:
  print('A lua está linda')
  print('Vai chegar a hora do curso')

idade = 24

if idade >= 18:
  print('Você já pode beber, mas com moderação')
else:
  print('Você não pode beber')

temperatura = 20

if temperatura <= 30:
  print('Aceitável')
else: 
  print('Socorro está muito quente')

altura = 1.66

if altura > 1.80:
  print('O João é alto')
else:
  print('O João é anão')

quente = True
gosta_praia = False

if quente == False:
  print('Está quente')
else:
  print('Está nublado')

"""- Geladeira:
  - Frutas
    - Maçã
    - Pera
    - Uva
"""

quente = False
gosta_praia = False
gosta_chocolate_quente = True

if quente == True:
  print('Está quente')
  if gosta_praia == True:
    print('Vá para a praia')
  else: 
    print('Não vá a praia')
else:
  print('Está frio')
  if gosta_chocolate_quente == True:
    print('Tome um chocolate quente')
  else:
    print('Não tome chocolate quente')

dia = input('Qual é o dia atual? ')

if dia == 'sabado':
  print('É fim de semana :D')
elif dia == 'domingo':
  print('É fim de semana :D')
else: 
  print('Não é fim de semana :(')

# 1, 3, 6 e 10  => Válido
# qualquer outro => Inválido

numero = 6

if numero == 1:
  print('é valido')
elif numero == 3:
  print('é valido')
elif numero == 6:
  print('é valido')
elif numero == 10:
  print('é valido')
else:
  print('é inválido')

"""# Operadores Lógicos
Servem para fazer uma condição composta

E => Ambas precisam ser verdade
OU => Pelo Menos UMA precisa ser verdade

Ex:

Se for manhã E estiver sol
Se for sábado OU domingo
E => AND
OU => OR
"""

dia = input('Qual é o dia atual? ')

if dia == 'sabado' or dia == 'domingo':
  print('É fim de semana :D')
else: 
  print('Não é fim de semana :(')

# 1, 3, 6 e 10  => Válido
# qualquer outro => Inválido

numero = 10

if numero == 1:
  print('é valido')
elif numero == 3:
  print('é valido')
elif numero == 6:
  print('é valido')
elif numero == 10:
  print('é valido')
else:
  print('é inválido')

numero = 7

if numero == 1 or numero == 3 or numero == 6 or numero == 10:
  print('É válido')
else:
  print('É inválido')

horario = 'manha'
sol = False

if horario == 'manha' and sol == True:
  print('Está uma manhã ensolarada')
else:
  print('Está nublado e não gosto')

meu_nome = 'João'
nome = input('Digite seu nome: ')

meu_sobrenome = 'Arruda'
sobrenome = input('Digite seu sobrenome: ')

if nome == meu_nome and sobrenome == meu_sobrenome:
  print('Você é o João Arruda')
else:
  print('Você não é o João Arruda')

numero_sorte = 2

numero = int(input('Escolha um numero: '))

if numero != 2:
  print('errou o numero')
else:
  print('acertou, parabéns!')

"""#Laços de Repetição

É uma excelente forma de evitar repetição de código.

Ele vai executar n vezes uma operação.

n => Quantidade de vezes definida.
"""

# De 1 até 10 vamos printar todos os numeros
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
# Na programação o Minimo (1) é INCLUSIVO => Ele existe
# Já é Maximo (10) é EXCLUSIVO => Ele não existe

# Até 11 vamos printar todos os numeros
print(0)
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
# Na programação o Minimo (1) é INCLUSIVO => Ele existe
# Já é Maximo (10) é EXCLUSIVO => Ele não existe

for numero in range(1,10):
  print(numero)

for numero in range(1,10):
  print(numero)

for numero in range(10):
  print(numero)

"""for => Nossa palavra-chave para Repetição.
variavel => O dado que estamos trabalhando no momento atual.
in => Nossa palavra-chave para "onde vamos repetir?"
invervalo/sequencia => O que vamos repedir
"""

for numero in range(10):
  print(numero)


#    for         numero       in          range(10)
# para cada      numero       no      intervalo até 10

for numero in range(1, 14):
  print('O número atual é:', numero)

for numero in range(1, 11):
  print('O número atual é:', numero)
  if numero == 4:
    print('É o numero 4')
  if numero == 8:
    print('É o numero 8')

nomes = ['João', 'Maria', 'Valquiria', 'Valeria']

for nome in nomes:
  print('O nome atual é', nome)
  if nome == 'João':
    print('(Ou Jú)')

notas = [6, 7.5, 9, 10, 3, 5]

soma = 0

for nota in notas:
  soma = soma + nota

print('A soma é', soma)

media = soma / len(notas)

print('A média é', media)

# len => Tamanho em ingles (abreviação)
      #  1  2   
notas = [6, 7.5]
len(notas)

# range = intervalo em ingles
# range(1, 10) => intervalo de 1 até 10

lista1 = ['A', 'B', 'C']
lista2 = [1, 2, 3, 4, 5]

tam_lista1 = len(lista1)
tam_lista2 = len(lista2)

print(tam_lista1)
print(tam_lista2)

"""# Função
Toda função é uma rotina.

Eu defino (def) uma rotina e a executo quantas vezes quiser.

É uma excelente forma de deixar nosso dinâmico e sem repetição.
"""

# Definindo a função
def nome_funcao(): 
  # Código da função
  print('Codigo da função')

# Chamando a função
nome_funcao()

def mostrar_nome():
  print('João Arruda')

mostrar_nome()

"""# Parâmetro/Argumento da função
É uma maneira de enviar dados para a função
"""

def mostrar_nome(nome_atual):
  print(nome_atual)
  
mostrar_nome('João')
mostrar_nome('Maria')
mostrar_nome('Valquiria')
mostrar_nome('Valeria')

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2 
  print(media)


primeira_nota = float(input('Sua primeira nota: '))
segunda_nota = float(input('Sua segunda nota: '))

calcular_media(primeira_nota, segunda_nota)

"""# Return

Quando queremos retornar um valor da função, ou seja, a função devolve um valor calculado, nós usamos o Return.
"""

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media1 = soma / 2 


calcular_media(10,8)

# Deu erro pois não usamos o return
print(media1)

def calcular_media(nota1, nota2):
  soma = nota1 + nota2
  media = soma / 2 
  return media


media_calculada = calcular_media(9,8)

print(media_calculada)

# IMC => PESO (KG) / ALTURA (M)²

def numero_quadrado(numero):
  quadrado = numero * numero 
  return quadrado 

def calcular_imc(peso, altura):
  altura_quadrada = numero_quadrado(altura)
  meu_imc = peso / altura_quadrada

  return meu_imc

imc = calcular_imc(62, 1.66)
print(imc)

# IMC => PESO (KG) / ALTURA (M)²

def numero_quadrado(numero):
  quadrado = numero * numero 
  return quadrado 

def calcular_imc(peso, altura):
  altura_quadrada = numero_quadrado(altura)
  meu_imc = peso / altura_quadrada

  return meu_imc

def classificar_imc(meu_imc):
  if imc < 18.5:
    print('Magreza')
  elif imc >= 18.5 and imc < 25:
    print('Normal')
  elif imc >= 25 and imc < 30:
    print('Sobrepeso')
  elif imc >= 30 and imc < 40:
    print('Obesidade')
  else:
    print('Obesidade Grave')

imc = calcular_imc(62, 1.66)

print('Seu IMC é:', imc)

print('Sua classificação é:')
classificar_imc(imc)

