# -*- coding: utf-8 -*-
"""Média.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17tuv0gAq9nsKRjLWvByeIpjYwF-pOxKW
"""

nota1 = 7.5
nota2 = 4.8

# Definimos o que é "Verificar uma Aprovação"
def verificar_aprovacao():
  media = calcular_media([nota1, nota2])

  if media >= 6:
    print("O aluno foi aprovado!")
  else:
    print("O aluno foi reprovado!")

# Definimos o que é "Calcular a Média"
def calcular_media(notas):
  quantidade = len(notas)

  soma = 0
  for nota in notas:
    soma = soma + nota

  media = soma / quantidade

  return media

# Chamamos (excutamos) a função de Verificar Aprovação
verificar_aprovacao()

