# -*- coding: utf-8 -*-
"""Notas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXgDczJNMAZDEjL-koF5oSEXmWHHJCHl
"""

nome = input("insira o seu nome:   ")

nota1 = float(input("sua primeira nota:  ")) 
nota2 = float(input("sua segunda nota:  ")) 

print("Olá",  nome,   "sua notas foram:")
print(nota1, "e", nota2)

soma = nota1 + nota2

media = nota1 + nota2 / 2

print("Sua média é", media)

